### ISSUE TITLE
Are there plans to add 5.X features to the documentation?

### ISSUE THREAD

**Issue by wang1212** [ecomfe/zrender-doc#9]
The **5.X** version has some incompatible changes compared to the **4.X** version, such as the `text` element, which is of course mentioned in the echarts documentation, and the API for state management such as `useState` is Very useful, but seems to know how to use it only by looking at the source code.

---

So, are there plans to update the 5.x features to the documentation? Since I see that the number of contributors to this repository is very small, should it accept contributions from external developers?

**Comment by Ovilia** [comment]
Most of the doc is up-to-date. Please help make a PR or issue if you find some of it is not.
